project_name: urlcodec

env_files:
  github_token: ./.goreleaser_github_token

builds:
- binary: urlcodec

archives:
  -
    id: urlcodec

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256