# This file was generated by GoReleaser. DO NOT EDIT.
class Urlcodec < Formula
  desc "URL Encode and Decode CLI"
  homepage "https://github.com/wakumaku/urlcodec"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wakumaku/urlcodec/releases/download/v0.0.2/urlcodec_0.0.2_darwin_amd64.tar.gz"
    sha256 "9045c51d0fd3759d44f833571410bf4f3d1aa5bb6d9d39e52f2bf80bfdb85605"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/wakumaku/urlcodec/releases/download/v0.0.2/urlcodec_0.0.2_linux_amd64.tar.gz"
      sha256 "ea29afe4c71fc6358f09b481480e483429eaffaec499e8cf67caf7c1abdb8692"
    end
  end

  def install
    bin.install "program"
  end
end
