# This file was generated by GoReleaser. DO NOT EDIT.
class Urlcodec < Formula
  desc "URL Encode and Decode CLI"
  homepage "https://github.com/wakumaku/homebrew-urlcodec"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wakumaku/homebrew-urlcodec/releases/download/v0.0.4/urlcodec_0.0.4_darwin_amd64.tar.gz"
    sha256 "1098cee33ffe46b0c1f68f1964da6573aa6b4a2bec4465dc4fe059d5c967254c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/wakumaku/homebrew-urlcodec/releases/download/v0.0.4/urlcodec_0.0.4_linux_amd64.tar.gz"
      sha256 "17cc13aa898fd2fdeb14476ca50c6938a062624870fe9afc071a455c24058de1"
    end
  end

  def install
    bin.install "urlcodec"
  end
end
